spring.application.name=chantier-management

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3307/construction_db
spring.datasource.username=....
spring.datasource.password=......

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=.......
jwt.expiration=604800000

logging.level.org.springframework.security=DEBUG
logging.level.com.medplatform=DEBUG
